version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
        environment:
          ECR_REPOSITORY_NAME: cqrs
    steps:
      - checkout
      - run:
          name: Install AWS cli
          working_directory: /
          command: aws --version
      - run:
          name: Build and push docker image
          working_directory: webservice/
          command: |
            if [ `aws ecr describe-repositories --region us-east-1 --repository-names $ECR_REPOSITORY_NAME | grep "$ECR_REPOSITORY_NAME" | wc -l` == 0 ]; then
              echo "Creating ECR repository $ECR_REPOSITORY_NAME"
              aws ecr create-repository --repository-name $ECR_REPOSITORY_NAME --region us-east-1
            else
              echo "ECR Repository $ECR_REPOSITORY_NAME already exists"
            fi
            echo ecr describe-repositories --repository-name $ECR_REPOSITORY_NAME --region us-east-1 | grep "repositoryUri"
            docker build -t $ECR_REPOSITORY_NAME .
      - run:
          name: Install Terraform
          working_directory: /
          command: |
            apk update && apk add ca-certificates && update-ca-certificates && apk add openssl
            wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            apk add unzip
            unzip terraform_0.11.7_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Install git (required for Terraform modules retrieval)
          working_directory: /
          command: apk add git
      - run:
          name: Apply terraform changes
          working_directory: infrastructure/
          command: |
            terraform init
            terraform apply -auto-approve
