version: 2
jobs:
  build:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - checkout
      - run:
          name: Check AWS cli is installed
          working_directory: /
          command: aws --version
      - run:
          name: Install Terraform
          working_directory: /
          command: |
            apk update && apk add ca-certificates && update-ca-certificates && apk add openssl
            wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            apk add unzip
            unzip terraform_0.11.7_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Apply terraform changes
          working_directory: infrastructure/
          command: |
            terraform init
            terraform apply -auto-approve
