version: 2
jobs:
  build:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - checkout
      - run:
          name: Check AWS cli is installed
          working_directory: /
          command: aws --version
      - run:
          name: Install Terraform
          working_directory: /
          command: |
            apt-get install unzip
            wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            unzip terraform_0.11.7_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform --version
