version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install AWS cli
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get install -y python3-pip
            pip install awscli --upgrade --user
      - run:
          name: Install Terraform
          working_directory: /
          command: |
            apt-get install unzip
            wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            unzip terraform_0.11.7_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform --version
